### PR TITLE
Directly reset callbacks without going through lwip functions (fix #30)

### LINKED ISSUE #30: Panic in AsyncTCP due to sudden WiFi disconnection
### IDE / Tooling

Arduino (IDE/CLI)

### What happened?

Description
I'm encountering a panic in AsyncTCP (version 3.3.5) when the WiFi connection is suddenly lost during an active TCP session. The issue seems related to the tcp_sent function in lwIP and occurs intermittently when the connection is dropped unexpectedly.

I've used AsyncTCP in multiple functions across my project (including both HTTP requests and MQTT connections). Eventually, I was forced to replace those functions with esp-idf esp_http_client to prevent the panic. After switching to esp-idf's native client, the panic no longer occurred.

The environment is extremely noisy, and the network connection frequently drops due to interference. It feels like the DNS resolution fails or becomes unresponsive at times, but regardless of the cause, the device panics and resets.

Even though I check WiFi status (WiFi.status()) and use flags (onEvent SYSTEM_EVENT_STA_GOT_IP) to ensure the connection is stable before sending data, the panic still happens occasionally during the transmission process when the connection drops unexpectedly.

Additional Information:
The environment is noisy, and the network connection is highly unstable.
DNS resolution seems to fail or become unresponsive at times, which might contribute to the issue.
I tested the WiFi connection status (WiFi.status()) before sending data and used event handlers (onEvent SYSTEM_EVENT_STA_GOT_IP) to set flags for connection status.
Despite these checks, the panic still occurs intermittently during data transmission if the connection is lost mid-process.
After replacing AsyncTCP with esp_http_client from esp-idf, the problem disappeared completely.
This happens with both AsyncTCP and AsyncMqttClient.

this code work in other device (other location)) but in thsi location painic ocuure 4-5 times a day!

System Information
Board: ESP32-S3
ESP32 Arduino Core: 2.3.4
AsyncTCP Version: 3.3.5
ESP-IDF Version: 3.1.2

### Stack Trace

PC: 0x40376711 0x4037670E 0x4037E0CD 0x40384D59 0x420629E7 0x42020C6E 0x42020CA4 0x42020FEE 0x42021023 0x4037EE16
0x00000000: ?? ??:0
0x40376711: panic_abort at esp_system/panic.c:463
0x4037670e: panic_abort at esp_system/panic.c:463
0x4037e0cd: esp_system_abort at esp_system_chip.c:92
0x40384d59: __assert_func at assert.c:80
0x420629e7: tcp_sent at lwip/src/core/tcp.c:2076 (discriminator 1)
0x42020c6e: AsyncClient::_error(signed char) at AsyncTCP.cpp:1055
0x42020ca4: AsyncClient::_s_error(void*, signed char) at AsyncTCP.cpp:1503
0x42020fee: _handle_async_event(lwip_tcp_event_packet_t*) at AsyncTCP.cpp:271
0x42021023: _async_service_task(void*) at AsyncTCP.cpp:294
0x4037ee16: vPortTaskWrapper at port.c:139

### Minimal Reproductible Example (MRE)

[test.txt](https://github.com/user-attachments/files/18815010/test.txt)

### I confirm that:

- [x] I have read the documentation.
- [x] I have searched for similar discussions.
- [x] I have searched for similar issues.
- [x] I have looked at the examples.
- [x] I have upgraded to the lasted version of AsyncTCP.

### PR DESCRIPTION
**Pull request by mathieucarbou**
fix #30

### CODE REVIEW

**Comment by willmmiles** [comment]
At least as I understood the documentation, LwIP frees the `tcp_pcb` when `_tcp_error` returns.  Any dereferencing of `_pcb` in `AsyncClient::_error`, or *any* other event callback after that point, is a use-after-free and will result in corrupting memory.  This was the major impetus behind the redesign in #21.

**Comment by mathieucarbou** [comment]
> At least as I understood the documentation, LwIP frees the `tcp_pcb` when `_tcp_error` returns. Any dereferencing of `_pcb` in `AsyncClient::_error`, or _any_ other event callback after that point, is a use-after-free and will result in corrupting memory. This was the major impetus behind the redesign in #21.

@me-no-dev suggested also another approach I will try, which is to immediately cleanup and after send the event in the queue (for the user callback only)

**Comment by willmmiles** [comment]
You can skip most of the API cleanup as the pcb is about to be freed; none of the other callbacks will get called again anyways.  The key cleanup is to invalidate the `close_slot` so that any in-flight operation on the async thread won't accidentally try to dereference the now-released pcb.

File: src/AsyncTCP.cpp [hunk 1]
```diff
@@ -448,8 +448,23 @@ static int8_t _tcp_sent(void *arg, struct tcp_pcb *pcb, uint16_t len) {
...
+    if (client->_pcb->state == LISTEN) {
+      client->_pcb->sent = NULL;
+      client->_pcb->recv = NULL;
+      client->_pcb->errf = NULL;
+      client->_pcb->poll = NULL;
+      client->_pcb->pollinterval = 0;
+    }
+    client->_pcb->callback_arg = NULL;
+    client->_pcb = nullptr;
+    client->_free_closed_slot();
```
Comment (mathieucarbou) [inline src/AsyncTCP.cpp:464]: @me-no-dev @willmmiles : not sure if this can be called directly from lwip thread, or if it has to stay like before and executed from async_tcp task...

**Comment by mathieucarbou** [comment]
@willmmiles @me-no-dev : just a heads up for this issue PR:

We had 2 users having the issue (@hosseinaghaie and @moreArti - see #30).

@moreArti was able to test and confirm that the initial fix works. The initial fix was just about cleaning up states:

```c++
void AsyncClient::_error(int8_t err) {
  if (_pcb) {
    TCP_MUTEX_LOCK();
    tcp_arg(_pcb, NULL);
    if (_pcb->state == LISTEN) {
      // tcp_sent(_pcb, NULL);
      _pcb->sent = NULL;
      // tcp_recv(_pcb, NULL);
      _pcb->recv = NULL;
      // tcp_err(_pcb, NULL);
      _pcb->errf = NULL;
      // tcp_poll(_pcb, NULL, 0);
      _pcb->poll = NULL;
      _pcb->pollinterval = 0;
    }
    TCP_MUTEX_UNLOCK();
    _free_closed_slot();
    _pcb = NULL;
  }
```

I have update this PR yesterday to update the fix with something we discussed with @me-no-dev : cleanup earlier within the lwip thread and only do the callbacks from the async_tcp task.

I am not sure about the `_free_closed_slot()`, if can be done earlier too, or if it has to be executed from the async_tcp task.

Do you know ?

Also, I have asked @moreArti to test again with this new fix.

Thanks everybody!

File: src/AsyncTCP.cpp (hunk 1 above)
Comment (willmmiles) [reply src/AsyncTCP.cpp:464]: Yes, it should be called immediately on the LwIP thread, so any subsequent `tcpip_api_call`s by an in-flight callback on this client are errored out instead of potentially accessing an invalid pcb.

(Unfortunately it does not catch the case where a `tcpip_api_call` is already waiting -- the old closed slot value has been copied to the `tcp_api_call_t` struct.  In fact, it's even technically possible that the closed slot is reallocated before the tcpip_api_call gets executed!)

File: src/AsyncTCP.cpp [hunk 2]
```diff
@@ -448,8 +448,23 @@ static int8_t _tcp_sent(void *arg, struct tcp_pcb *pcb, uint16_t len) {
...
+  AsyncClient *client = reinterpret_cast<AsyncClient *>(arg);
+  if (client && client->_pcb) {
+    if (client->_pcb->state == LISTEN) {
+      client->_pcb->sent = NULL;
+      client->_pcb->recv = NULL;
+      client->_pcb->errf = NULL;
+      client->_pcb->poll = NULL;
+      client->_pcb->pollinterval = 0;
+    }
+    client->_pcb->callback_arg = NULL;
```
[the remark this answers is not in the document]
Comment (mathieucarbou) [reply src/AsyncTCP.cpp:462]: Is there any reason why we would want to use the lwip functions ? 
They are essentially doing the same thing, but with extra checks on states.

[the remark this answers is not in the document]
Comment (me-no-dev) [reply src/AsyncTCP.cpp:462]: it will be OK to use the LwIP functions, because we do not end up in the case that the PCB is in different actual state, so the checks will pass. Using the functions ensures that if the pcb structure ever changes, it will still be compatible (as doubtful as that actually is)

File: src/AsyncTCP.cpp [hunk 3]
```diff
@@ -448,8 +448,23 @@ static int8_t _tcp_sent(void *arg, struct tcp_pcb *pcb, uint16_t len) {
   return ERR_OK;
 }
 
-static void _tcp_error(void *arg, int8_t err) {
+void AsyncClient::_tcp_error(void *arg, int8_t err) {
```
Comment (me-no-dev) [inline src/AsyncTCP.cpp:451]: what is the reason behind making it a class member?

Comment (mathieucarbou) [reply src/AsyncTCP.cpp:451]: to access private fields.

File: src/AsyncTCP.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (mathieucarbou) [reply src/AsyncTCP.cpp]: updated

**Review by me-no-dev — APPROVED** [review]
